services:
  backend:
    container_name: backend
    build:
      context: ../server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    env_file: .env
    expose:
      - 8080
    depends_on:
      - ai_service

  nginx:
    container_name: nginx
    image: nginx:1.26.3
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../client/dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend

  ai_service:
    container_name: ai_service
    build:
      context: ../ai_service
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000 # Cổng của AI service (FastAPI)
    expose:
      - 8000

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email hieu.le0811@hcmut.edu.vn -d doctorhere.dev --agree-tos

  ai_agent:
    build:
      context: ../ai_agent
      dockerfile: Dockerfile
    container_name: ai_agent
    ports:
      - "8001:8001" 
    env_file: .env
    expose:
      - 8001
    restart: unless-stopped
#docker compose -p doctor-here down
#docker compose -p doctor-here up -d --build
