const { DataTypes } = require("sequelize");

// CREATE TABLE "Chi_dinh_an_kq_cua_bac_si" (
//   "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
//   "ma_benh_nhan" varchar(9),
//   "ma_bac_si" varchar(9),
//   "an_kq" boolean default false,
//   UNIQUE ("ma_benh_nhan", "ma_bac_si"),
//   PRIMARY KEY ("id"),
//   FOREIGN KEY ("ma_benh_nhan") REFERENCES "Benh_nhan" ("ma_benh_nhan") ON DELETE NO ACTION ON UPDATE NO ACTION,
//   FOREIGN KEY ("ma_bac_si") REFERENCES "Bac_si" ("ma_bac_si") ON DELETE NO ACTION ON UPDATE NO ACTION
// )

module.exports = (sequelize) => {
  return sequelize.define(
    "ConfidentialDoctor",
    {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      ma_benh_nhan: {
        type: DataTypes.STRING(9),
        allowNull: false,
        references: {
          model: "Benh_nhan",
          key: "ma_benh_nhan",
        },
        onDelete: "NO ACTION",
        onUpdate: "NO ACTION",
        unique: "uq_chi_dinh_an_kq_cua_bac_si",
      },
      ma_bac_si: {
        type: DataTypes.STRING(9),
        allowNull: false,
        references: {
          model: "Bac_si",
          key: "ma_bac_si",
        },
        onDelete: "NO ACTION",
        onUpdate: "NO ACTION",
        unique: "uq_chi_dinh_an_kq_cua_bac_si",
      },
      an_kq: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: false,
      },
    },
    {
      tableName: "Chi_dinh_an_kq_cua_bac_si",
      timestamps: false,
    }
  );
};
