const { DataTypes } = require("sequelize");

// CREATE TABLE "Cuoc_hoi_thoai" (
//     "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
//     "thoi_diem_tao" TIMESTAMP,
//     "ma_bac_si" varchar(9),
//     "ma_benh_nhan" varchar(9),
//     PRIMARY KEY ("id")
//     constraint "uq_cuoc_hoi_thoai" UNIQUE ("ma_bac_si", "ma_benh_nhan")
//   );
module.exports = (sequelize) => {
  return sequelize.define(
    "Conversation",
    {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      thoi_diem_tao: {
        type: DataTypes.DATE,
        defaultValue: DataTypes.NOW,
      },
      ma_bac_si: {
        type: DataTypes.STRING(9),
        allowNull: true,
        references: {
          model: "Bac_si",
          key: "ma_bac_si",
        },
        onDelete: "NO ACTION",
        onUpdate: "NO ACTION",
        unique: "uq_cuoc_hoi_thoai",
      },
      ma_benh_nhan: {
        type: DataTypes.STRING(9),
        allowNull: true,
        references: {
          model: "Benh_nhan",
          key: "ma_benh_nhan",
        },
        onDelete: "NO ACTION",
        onUpdate: "NO ACTION",
        unique: "uq_cuoc_hoi_thoai",
      },
      thoi_diem_tin_nhan_cuoi: {
        type: DataTypes.DATE,
        allowNull: true,
        defaultValue: null,
      },
      is_ai_agent: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: false,
      }
    },
    {
      tableName: "Cuoc_hoi_thoai",
      timestamps: false,
    }
  );
};
