const {DataTypes} = require('sequelize');
// CREATE TABLE "Ket_qua_kham_benh" (
//     "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
//     "ket_qua_chan_doan" VARCHAR(255),
//     "ghi_chu_them" VARCHAR(255),
//     "ma_cuoc_hen" INTEGER,
//     "ma_bac_si" varchar(9),
//     PRIMARY KEY ("id")
//   );
module.exports = (sequelize) => {
    return sequelize.define('Diagnosis', {
        id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true,
        },
        ket_qua_chan_doan: {
            type: DataTypes.STRING,
            allowNull: true,
        },
        ghi_chu_them: {
            type: DataTypes.STRING,
            allowNull: true,
        },
        ma_cuoc_hen: {
            type: DataTypes.INTEGER,
            allowNull: false,
            references: {
                model: 'Cuoc_hen',
                key: 'id',
                onDelete: 'NO ACTION',
                onUpdate: 'NO ACTION',
            }
        },
        ma_bac_si: {
            type: DataTypes.STRING(9),
            allowNull: false,
            references: {
                model: 'Bac_si',
                key: 'ma_bac_si',
                onDelete: 'NO ACTION',
                onUpdate: 'NO ACTION',
            }
        }
    }, {
        tableName: 'Ket_qua_kham_benh',
        timestamps: false,
    });
};