const {DataTypes} = require('sequelize');
// CREATE TABLE "Thong_bao_tin_nhan" (
//     "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
//     "thoi_diem_thong_bao" TIMESTAMP,
//     "noi_dung" VARCHAR(255),
//     "id_tin_nhan" INTEGER,
//     PRIMARY KEY ("id")
//   );
module.exports = (sequelize) => {
    return sequelize.define("MessageNoti", {
        id: {
            type: DataTypes.INTEGER,
            autoIncrement: true,
            primaryKey: true
        },
        thoi_diem_thong_bao: {
            type: DataTypes.DATE,
            allowNull: true
        },
        noi_dung: {
            type: DataTypes.STRING(255),
            allowNull: true
        },
        id_tin_nhan: {
            type: DataTypes.INTEGER,
            allowNull: true,
            references: { model: 'Message', key: 'id' },
            onUpdate: 'NO ACTION', 
            onDelete: 'NO ACTION'
        }
    }, {
        tableName: "Thong_bao_tin_nhan",
        timestamps: false
    });
}