const { DataTypes, FLOAT } = require("sequelize");
// CREATE TABLE "Danh_gia" (
//     "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
//     "diem_danh_gia" varchar(2),
//     "noi_dung" VARCHAR(255),
//     "thoi_diem" TIMESTAMP,
//     "id_cuoc_hen" INTEGER,
//     "ma_benh_nhan_danh_gia" varchar(9),
//     PRIMARY KEY ("id")
//   );
module.exports = (sequelize) => {
  return sequelize.define(
    "Rating",
    {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      diem_danh_gia: {
        type: FLOAT,
        allowNull: false,
      },
      noi_dung: {
        type: DataTypes.STRING(255),
        allowNull: false,
      },
      thoi_diem: {
        type: DataTypes.DATE,
        allowNull: false,
      },
      id_cuoc_hen: {
        type: DataTypes.INTEGER,
        allowNull: false,
        references: {
          model: "Cuoc_hen",
          key: "id",
        },
      },
      ma_benh_nhan_danh_gia: {
        type: DataTypes.STRING(9),
        allowNull: false,
        references: {
          model: "Benh_nhan",
          key: "ma_benh_nhan",
        },
      },
      ma_bac_si: {
        type: DataTypes.STRING(9),
        allowNull: false,
        references: {
          model: "Bac_si",
          key: "ma_bac_si",
        },
      },
    },
    {
      tableName: "Danh_gia",
      timestamps: false,
    }
  );
};
