version: '3.8'
services:
  ai-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-agent
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
