# Dockerfile
FROM python:3.12.1-slim

# Cài đặt các thư viện hệ thống cần thiết
RUN apt-get update && apt-get install -y build-essential

# Tạo thư mục làm việc
WORKDIR /app

# Copy toàn bộ dự án vào container
COPY . .

# Cài đặt thư viện Python
RUN pip install --no-cache-dir -r requirements.txt

# Chạy FastAPI server
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
