const {DataTypes} = require('sequelize');
// CREATE TABLE "Cuoc_hen" (
//     "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
//     "pttt" VARCHAR(255),
//     "van_ban_bo_sung" VARCHAR(255),
//     "dia_chi_phong_kham" VARCHAR(255),
//     "trang_thai" VARCHAR(255),
//     "thoi_diem_tao" timestamp,
//     "ma_bac_si" varchar(9),
//     "ma_benh_nhan_dat_hen" varchar(9),
//     PRIMARY KEY ("id")
//   );
module.exports = (sequelize) => {
    return sequelize.define('Appointment', {
        id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true,
        },
        pttt: {
            type: DataTypes.STRING,
            allowNull: true,
        },
        van_ban_bo_sung: {
            type: DataTypes.STRING,
            allowNull: true,
        },
        dia_chi_phong_kham: {
            type: DataTypes.STRING,
            allowNull: true,
        },
        trang_thai: {
            type: DataTypes.STRING,
            allowNull: true,
        },
        thoi_diem_tao: {
            type: DataTypes.DATE,
            allowNull: false,
        },
        ma_bac_si: {
            type: DataTypes.STRING(9),
            allowNull: false,
            references: {
                model: 'Bac_si',
                key: 'ma_bac_si',
                onDelete: 'NO ACTION',
                onUpdate: 'NO ACTION',
            }
        },
        ma_benh_nhan_dat_hen: {
            type: DataTypes.STRING(9),
            allowNull: false,
            references: {
                model: 'Benh_nhan',
                key: 'ma_benh_nhan',
                onDelete: 'NO ACTION',
                onUpdate: 'NO ACTION',
            }
        }
    }, {
        tableName : 'Cuoc_hen',
        timestamps : false
    });
}