const {DataTypes} = require('sequelize');

// CREATE TABLE "Thong_bao_cuoc_goi" (
//     "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
//     "thoi_diem_thong_bao" TIMESTAMP,
//     "noi_dung" VARCHAR(255),
//     "cuoc_goi" INTEGER,
//     PRIMARY KEY ("id")
//   );
module.exports = (sequelize) => {
    return sequelize.define('CallNoti', {
        id: {
            type: DataTypes.INTEGER,
            autoIncrement: true,
            primaryKey: true
        },
        thoi_diem_thong_bao: {
            type: DataTypes.DATE,
            allowNull: false
        },
        noi_dung: {
            type: DataTypes.STRING(255),
            allowNull: false
        },
        cuoc_goi: {
            type: DataTypes.INTEGER,
            allowNull: false,
            references: {
                model: 'Cuoc_goi',
                key: 'id'
            },
            onUpdate: 'NO ACTION',
            onDelete: 'NO ACTION'
        }
    }, {
        tableName: 'Thong_bao_cuoc_goi',
        timestamps: false
    });
}