const {DataTypes} = require('sequelize');
// CREATE TABLE "Cuoc_goi" (
//     "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
//     "trang_thai" VARCHAR(50),
//     "thoi_diem_goi" TIMESTAMP,
//     "thoi_diem_ket_thuc" TIMESTAMP,
//     "id_cuoc_hen" INTEGER,
//     "ben_goi_di" CHAR(3),--BN or BS
//     PRIMARY KEY ("id")
//   );
module.exports = (sequelize) => {
    return sequelize.define('Call', {
        id: {
            type: DataTypes.INTEGER,
            autoIncrement: true,
            primaryKey: true
        },
        trang_thai: {
            type: DataTypes.STRING(50),
            allowNull: false
        },
        thoi_diem_goi: {
            type: DataTypes.DATE,
            allowNull: false
        },
        thoi_diem_ket_thuc: {
            type: DataTypes.DATE,
            allowNull: true
        },
        id_cuoc_hen: {
            type: DataTypes.INTEGER,
            allowNull: false,
            references: {
                model: 'Cuoc_hen',
                key: 'id'
            },
            onUpdate: 'NO ACTION',
            onDelete: 'NO ACTION'
        },
        ben_goi_di: {
            type: DataTypes.CHAR(3),
            allowNull: false
        }
    }, {
        tableName: 'Cuoc_goi',
        timestamps: false
    });
}