const {DataTypes} = require('sequelize');
// CREATE TABLE "Tin_nhan" (
//     "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
//     "kieu_noi_dung" VARCHAR(255),
//     "noi_dung_van_ban" VARCHAR(255),
//     "media_url" VARCHAR(255),
//     "thoi_diem_gui" TIMESTAMP,
//     "thoi_diem_da_xem" TIMESTAMP,
//     "cuoc_hoi_thoai" INTEGER,
//     "ben_gui_di" CHAR(3),
//     PRIMARY KEY ("id")
//   );
module.exports = (sequelize) => {
    return sequelize.define('Message', {
        id: {
            type: DataTypes.INTEGER,
            autoIncrement: true,
            primaryKey: true
        },
        kieu_noi_dung: {
            type: DataTypes.STRING(255),
            allowNull: false
        },
        noi_dung_van_ban: {
            type: DataTypes.STRING(255),
            allowNull: true
        },
        media_url: {
            type: DataTypes.STRING(255),
            allowNull: true
        },
        thoi_diem_gui: {
            type: DataTypes.DATE,
            defaultValue: DataTypes.NOW
        },
        thoi_diem_da_xem: {
            type: DataTypes.DATE,
            allowNull: true
        },
        cuoc_hoi_thoai: {
            type: DataTypes.INTEGER,
            allowNull: false,
            references: {
                model: "Cuoc_hoi_thoai",
                key: "id"
            },
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        },
        ben_gui_di: {
            type: DataTypes.CHAR(3),
            allowNull: false
        }
    }, {
        tableName: 'Tin_nhan',
        timestamps: false
    });
}