const { DataTypes } = require('sequelize');

// CREATE TABLE "Gio_hen" (
//     "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
//     "thoi_diem_bat_dau" TIMESTAMP UNIQUE,
//     "thoi_diem_ket_thuc" TIMESTAMP,
//     "ngay_lam_viec" DATE,
//     "available" BOOLEAN,
//     "id_ca_lam_viec" INTEGER,
//     PRIMARY KEY ("id")
//   );
module.exports = (sequelize) => {
    return sequelize.define('Timeslot', {
        id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true,
        },
        thoi_diem_bat_dau: {
            type: DataTypes.DATE,
            allowNull: false,
            unique: true,
        },
        thoi_diem_ket_thuc: {
            type: DataTypes.DATE,
            allowNull: false,
        },
        ngay_lam_viec: {
            type: DataTypes.DATEONLY,
            allowNull: false,
        },
        available: {
            type: DataTypes.BOOLEAN,
            allowNull: false,
        },
        id_ca_lam_viec: {
            type: DataTypes.INTEGER,
            allowNull: false,
            references: {
                model: 'Ca_lam_viec_trong_tuan',
                key: 'id',
                onDelete: 'NO ACTION',
                onUpdate: 'NO ACTION',
            },
        }
    }, {
        tableName: 'Gio_hen',
        timestamps: false,
    })
}